---
galaxy_info:
  author: foo <bar@baz.com>
  description: "Deploy OpenVPN server from the mps-openvpn config repo"
  min_ansible_version: "2.16.0"
  license: GPL-3.0-or-later
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - debian
    - debian13
    - trixie
    - services
    - openvpn
    - vpn
    - network
    - odem-services
dependencies:
  - role: odem.base.identity
