---
- name: Assert blackbox modules var set
  ansible.builtin.assert:
    that:
      - blackbox_modules | default({}) | length > 0
    fail_msg: >-
      blackbox_modules must be set (via host_vars or extra vars) to
      install the blackbox exporter.
- name: Install prometheus-blackbox-exporter package
  ansible.builtin.apt:
    name: prometheus-blackbox-exporter
    state: present
    update_cache: true
- name: Template blackbox-exporter default env file
  ansible.builtin.template:
    src: blackbox-exporter.default.j2
    dest: /etc/default/prometheus-blackbox-exporter
    owner: root
    group: root
    mode: "0644"
  notify: Restart blackbox-exporter
- name: Template blackbox-exporter systemd override unit
  ansible.builtin.template:
    src: blackbox-exporter.service.j2
    dest: /etc/systemd/system/prometheus-blackbox-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart blackbox-exporter
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
- name: Enable and start blackbox-exporter service
  ansible.builtin.systemd:
    name: prometheus-blackbox-exporter
    enabled: true
    state: started
