---
alloy_config_dir: /etc/alloy
alloy_custom_labels: "os=debian13,systype=hw,physloc=de"
alloy_host_collectors:
  - arp
  - bcache
  - bonding
  - boottime
  - btrfs
  - buddyinfo
  - cpu
  - diskstats
  - dmi
  - drm
  - edac
  - entropy
  - ethtool
  - filefd
  - filesystem
  - hwmon
  - interrupts
  - ksmd
  - lnstat
  - loadavg
  - logind
  - meminfo
  - meminfo_numa
  - mountstats
  - netclass
  - netdev
  - netstat
  - network_route
  - os
  - perf
  - powersupplyclass
  - pressure
  - processes
  - qdisc
  - rapl
  - schedstat
  - sockstat
  - softirqs
  - softnet
  - stat
  - sysctl
  - systemd
  - tcpstat
  - textfile
  - thermal_zone
  - time
  - timex
  - udp_queues
  - uname
  - vmstat
  - wifi
  - xfs
  - zfs
  - zoneinfo
