---
- name: Template scrape endpoint config
  ansible.builtin.template:
    src: scrape_endpoint.alloy.j2
    dest: "{{ alloy_config_dir }}/scrape_{{ item.name }}.alloy"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ alloy_metrics_scrape_endpoints }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Restart alloy
  when: alloy_metrics_scrape_endpoints | length > 0
