---

- name: Start monitoring compose stack
  ansible.builtin.shell: |
    docker compose up -d
  args:
    chdir: "{{ monitoring_repo_dest }}"
  become: true
  changed_when: false
  when: monitoring_enable_service | bool
