---
- name: Template pbs_exporter_scrape.alloy
  ansible.builtin.template:
    src: pbs_exporter_scrape.alloy.j2
    dest: "{{ alloy_config_dir }}/pbs_exporter_scrape.alloy"
    owner: root
    group: root
    mode: "0644"
  notify: Restart alloy
