---
- name: Create custom-metrics config directory
  ansible.builtin.file:
    path: "{{ custom_metrics_config_file | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Copy custom-metrics json config
  ansible.builtin.copy:
    src: custom-metrics.json
    dest: "{{ custom_metrics_config_file }}"
    owner: root
    group: root
    mode: "0644"
