---
- name: Install jq and python3 packages
  ansible.builtin.apt:
    name: [jq, python3]
    state: present
    update_cache: true
- name: Copy custom-metrics daemon script
  ansible.builtin.copy:
    src: monitoring-custom-metrics.bash
    dest: /usr/local/bin/monitoring-custom-metrics.bash
    owner: root
    group: root
    mode: "0755"
- name: Template custom-metrics default env file
  ansible.builtin.template:
    src: custom-metrics.default.j2
    dest: /etc/default/custom-metrics
    owner: root
    group: root
    mode: "0644"
  notify: Restart custom-metrics
- name: Template custom-metrics systemd unit
  ansible.builtin.template:
    src: custom-metrics.service.j2
    dest: /etc/systemd/system/custom-metrics.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart custom-metrics
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
- name: Enable and start custom-metrics service
  ansible.builtin.systemd:
    name: custom-metrics
    enabled: true
    state: started
