---
- name: Start OpenVPN compose services
  ansible.builtin.shell: |
    docker compose -f "{{ openvpn_compose_file }}" up -d --build
  args:
    chdir: "{{ openvpn_repo_dest }}"
  become: true
  changed_when: false
  when: openvpn_enable_service | bool

- name: Enable openvpn service
  ansible.builtin.systemd:
    name: openvpn-client
    state: started
    enabled: true
    daemon-reload: true
  when: openvpn_enable_main_client | bool
